### ISSUE TITLE
Python tests triggering "Unhandled exception at 0x00007FFAA2422C02 (mswsock.dll) in python_d.exe: 0xC0000005"

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/Pyjion#103]
Trigger is at https://github.com/python/cpython/blob/f614eeed5ef975a7e87f60a4e985d9d6df70bd6c/Python/thread_nt.h#L255

# test_asynchat
The thread 0x2514 has exited with code 0 (0x0).
Unhandled exception at 0x00007FFAA2422C02 (mswsock.dll) in python_d.exe: 0xC0000005: Access violation reading location 0x0000023900000008.

# test_asyncore, test_bz2, test_calendar
The thread 0x98 has exited with code 0 (0x0).
Unhandled exception at 0x00007FFAA2422C02 (mswsock.dll) in python_d.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by brettcannon** [comment]
The amount of tests with the same failure is high enough that I'm no longer going to bother reporting them here.

**Comment by brettcannon** [comment]
Various other failures like `test_poplib` mention `OSError: [WinError 10038] An operation was attempted on something that is not a socket`.

**Comment by DinoV** [comment]
Here's the full stack trace where we crash at shutdown:

000000e1`0ed8f6a0 00007ffa`8e397d0d mswsock!Tcpip4_WSHAddressToString+0x412
000000e1`0ed8f6d0 00007ffa`8e38703c mswsock!WSARecvEx+0x22d
000000e1`0ed8f710 00007ffa`92434fc8 mswsock!AcceptEx+0x1a8c
000000e1`0ed8f7c0 00007ffa`924328f1 ntdll!RtlActivateActivationContextUnsafeFast+0x108
000000e1`0ed8f820 00007ffa`9247c35e ntdll!LdrShutdownThread+0x151
000000e1`0ed8f920 00007ffa`8ecb8eb3 ntdll!RtlExitUserThread+0x3e
000000e1`0ed8f960 00007ffa`6b5da03b KERNELBASE!FreeLibraryAndExitThread+0x43
000000e1`0ed8f990 00007ffa`6b5da661 ucrtbased!register_onexit_function+0x2fb
000000e1`0ed8f9d0 00000000`770e325d ucrtbased!endthreadex+0x11
000000e1`0ed8fa00 00000000`76dba235 python36_d!PyThread_exit_thread+0x3d [c:\source\pyjion\python\python\thread_nt.h @ 257]
000000e1`0ed8fa30 00000000`770e388d python36_d!t_bootstrap+0x395 [c:\source\pyjion\python\modules\_threadmodule.c @ 1029]
000000e1`0ed8fae0 00007ffa`6b5da1bc python36_d!bootstrap+0x4d [c:\source\pyjion\python\python\thread_nt.h @ 176]
000000e1`0ed8fb30 00007ffa`6b5d9e13 ucrtbased!register_onexit_function+0x47c
000000e1`0ed8fb70 00007ffa`91728102 ucrtbased!register_onexit_function+0xd3
000000e1`0ed8fbc0 00007ffa`9247c2e4 KERNEL32!BaseThreadInitThunk+0x22
000000e1`0ed8fbf0 00000000`00000000 ntdll!RtlUserThreadStart+0x34
