### ISSUE TITLE
test_concurrent_futures fails

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/Pyjion#118]
======================================================================
FAIL: test_first_completed (test.test_concurrent_futures.ProcessPoolWaitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_concurrent_futures.py", line 204, in test_firs
t_completed
    self.assertEqual(set([future1]), done)
AssertionError: Items in the first set but not the second:
<Future at 0x1dc452a8468 state=running>
Items in the second set but not the first:
<Future at 0x1dc45820740 state=finished returned NoneType>

======================================================================
FAIL: test_first_exception (test.test_concurrent_futures.ProcessPoolWaitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_concurrent_futures.py", line 228, in test_firs
t_exception
    self.assertEqual(set([future1, future2]), finished)
AssertionError: Items in the second set but not the first:
<Future at 0x1dc45820740 state=finished returned NoneType>

----------------------------------------------------------------------

**Comment by brettcannon** [comment]
I'm still getting those two failures.

**Comment by DinoV** [comment]
I don't see either of those failures when just running:
.\python_d.exe ..\..\Lib\test\test_concurrent_futures.py
I'm trying it with -m now.  I did get 1 new failure which was that the test took to long, but I'm guessing that's intermittent as it passed completely for me before.

**Comment by brettcannon** [comment]
I always run tests like `python -m test -n -v test_concurrent_futures`.

I'll give it one more try to see if I can reproduce.

**Comment by brettcannon** [comment]
I'm still failing with those failures.

**Comment by brettcannon** [comment]
Considering these failures are time-based, I'm closing as fixed and assuming my laptop simply isn't fast enough.
