### ISSUE TITLE
test_gc crashes silently

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/Pyjion#119]
Execution suddenly ends after:
`test_trashcan (test.test_gc.GCTests) ...`

**Comment by brettcannon** [comment]
This is still failing for me.

**Comment by DinoV** [comment]
The same test_trashcan crash? It definitely passes for me when running ".\python_d.exe -m test -n -v test_gc"

**Comment by brettcannon** [comment]
Yep, exact same test.

**Comment by brettcannon** [comment]
My build got into a bad state; fresh clone has the test passing.
