### ISSUE TITLE
Any plan for Linux support?

### ISSUE THREAD

**Issue by evanfoster** [Microsoft/Pyjion#121]
I'm a bit of a know-nothing, so pardon if this is a stupid question.

Are there plans to make this buildable on (or at least for) Linux? A cursory glance through some of the source makes this seem non-trivial, but I figure I'd ask.

Thanks much!

**Comment by DinoV** [comment]
Ultimately yes.  That's one of the reasons we went with CoreCLR is because it also runs on Linux/Mac OS/X.  But right now we're focusing on compatibility and then we'll look at actually improving perf so it's a ways off.

**Comment by brettcannon** [comment]
This is currently blocked on #76. As @dinov said, we do plan on the support, it's just not a top issue until we prove that this is all worth it. :)

**Comment by evanfoster** [comment]
Awesome. I love this project and I hope it succeeds!

**Comment by brettcannon** [comment]
#125 will have a question answering this, so I'm going to close.
