### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [Microsoft/Pyjion#140]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") in [the destructor for the class "CorJitInfo"](https://github.com/Microsoft/Pyjion/blob/a70fdf07a4248d44e003f924c3a83d1aa449b203/Pyjion/jitinfo.h#L78 "Destructor for CorJitInfo").

**Comment by brettcannon** [comment]
Specifically, @elfring is referring to https://github.com/Microsoft/Pyjion/blob/a70fdf07a4248d44e003f924c3a83d1aa449b203/Pyjion/jitinfo.h#L85 be redundant.
