### ISSUE TITLE
PyPy and C extension support

### ISSUE THREAD

**Issue by fijal** [Microsoft/Pyjion#158]
Hello.

The main site of pyjion mentions that pypy does not support C extensions - that's blatantly not true, we've been improving our support for years now and it's more or less official that we support a lot of C extensions with PyPy 5 having full support for unmodified lxml (coming out today)

I'm not sure what wording you would like to use, so it's not a pull request :-)

**Comment by brettcannon** [comment]
Sorry about that; there was a critical "all" missing from that sentence.
