### ISSUE TITLE
How does it compare to...

### ISSUE THREAD

**Issue by xyproto** [Microsoft/Pyjion#181]
I see the FAQ has a section for "How does it compare to...".

How does Pyjion compare to [Nuitka](http://nuitka.net/) and [Shedskin](https://github.com/shedskin/shedskin)?

**Comment by brettcannon** [comment]
Nuitka and Shedskin are somewhat like Cython in that they are Python -> C++ transpilers. Pyjion is adding a JIT and thus isn't transpiling to another language.

**Comment by brettcannon** [comment]
https://github.com/Microsoft/Pyjion/commit/8c8de01ca133b3eb2f45b199d6a821251db64697

**Comment by xyproto** [comment]
Thanks for the update.
