### ISSUE TITLE
what is the timeline for Goal 2 (Develop a JIT module using CoreCLR utilizing the C API) ?

### ISSUE THREAD

**Issue by stonebig** [Microsoft/Pyjion#201]
milestonedating the project on Github would be nice

**Comment by brettcannon** [comment]
This project already works and provides a JIT module for a patched version of Python 3.5 since PyCon US 2016, so the timeline is "June 2016". :wink: 

Otherwise we don't provide dates because we have no schedule; we just work on this when we have time.
