### ISSUE TITLE
How are things going ?

### ISSUE THREAD

**Issue by stuaxo** [Microsoft/Pyjion#202]
The last update in this github was 3 months ago.   Is there a blog where we can see updates ?

Would be great to know if there has been any progress, particularly on other platforms - Linux, OSX has anyone tried this on Raspberry Pi ?

**Comment by brettcannon** [comment]
Closest we have to a blog is https://blogs.msdn.microsoft.com/pythonengineering/ . As for progress, the last 3 months have been spent upstreaming the changes for Python which just got in two weeks ago for [inclusion in Python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html#pep-523).

As for other platforms, that will probably require someone solving #76 or something similar.

**Comment by stuaxo** [comment]
Awesome, since the JIT is going to plug in to a standard python, will there be an easy way to install a JIT + get python to use it ?

**Comment by brettcannon** [comment]
@stuaxo that's the hope!
