### ISSUE TITLE
Use the frame evaluation API in Python 3.6

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/Pyjion#209]
We did add the API for this project, so we probably should use it. 😉

**Comment by datnamer** [comment]
Does this mean any JIT just needs to define operations on some primitives and get all of cpythpn for free, or would they have to reimplement everything still?

**Comment by brettcannon** [comment]
@datnamer It depends on the JIT. Pyjion, for instance, reimplements Python bytecode in CLR bytecode and then calls into the CPython API as necessary, but it's not required. Other JITs can do it however they want. The API I'm talking about is defined in https://www.python.org/dev/peps/pep-0523/.

**Comment by datnamer** [comment]
Gotcha thanks.
