### ISSUE TITLE
_Py_IDENTIFIER macro expansion issue

### ISSUE THREAD

**Issue by ethanhs** [Microsoft/Pyjion#216]
Im trying to build Pyjion using VS 2015 Update 3, cl `Compiler Version 19.00.24224`. When I build pyjion.sln, the build fails on _Py_IDENTIFIER macros. (The first one being [here](https://github.com/Microsoft/Pyjion/blob/master/Pyjion/intrins.cpp#L534)) It seems the designated initializer the macro expands to is not valid. This seems strange to me, and Im not sure where to proceed. The full output log is https://gist.github.com/ethanhs/2538016e4b8e9b80b20d8cd56e06a996

Im not sure why this would fail exactly. The same macro is used without issue in CPython sources, which worked fine with the same compiler. I was hoping to get some guidance on what the issue could be. I have tried re-installing Visual Studio to no avail.

**Comment by DinoV** [comment]
I think this is a bit of syntax VS 2015 doesn't support.  We should upgrade to VS 2017 where I'm assuming this is supported and works.  I've just been rolling back to the old macro definition when I've been building with VS 2015

**Comment by ethanhs** [comment]
@DinoV Thanks for the advice! When I build .net core, it seems to demand VS 2015, which is why I suggested we update to the new 2.0 preview 2. Does that make sense?

**Comment by DinoV** [comment]
Yep, upgrading does make sense...  I'll probably start tackling that after getting Unix support building first.

**Comment by ethanhs** [comment]
Actually, I think it might be better to move to core 2.0 first, as that should make changing to cmake easier (which I'd be happy to work on), which makes porting to Unix easier.

**Comment by brettcannon** [comment]
I'm fine with doing the .NET core 2.0 update first to make it easier if @DinoV doesn't have an issue with it.

**Comment by brettcannon** [comment]
I'm taking @DinoV 's silence as acceptance, so if you still have interest in this, @ethanhs , feel free to push a PR to upgrade to .NET Core 2.0 first.

**Comment by ethanhs** [comment]
I still have interest, time would be of the issue. :) I'll see what I can do.

**Comment by brettcannon** [comment]
@ethanhs 😄 It's open source, so no expectations and whatever you can spare is appreciated!

**Comment by ethanhs** [comment]
It turns out that C++11-17 do not support designated initializers, so this may be an issue with Python from what I can gather. [this commit](https://github.com/python/cpython/commit/5223f08e78efcfadb7fe2288fd48bb985d6ca7a7) added designated initializers. @brettcannon if you think I should, I can open a bug on bpo and make a patch.
