### ISSUE TITLE
Was PEP 523 implemented in the end ?

### ISSUE THREAD

**Issue by stuaxo** [microsoft/Pyjion#240]
The README says PEP 523 is going to happen in Python 3.6, did it ?

If so, it may be worth updating the README.

**Comment by brettcannon** [comment]
@stuaxo Yep, it's in: https://www.python.org/dev/peps/pep-0523/

**Comment by stuaxo** [comment]
I opened python, made a function and couldn't find a co_extra field on __code__ did it end up being something else.

Maybe I don't know how to read PEPs but I was expecting to see a python version number on the pep itself.

**Comment by brettcannon** [comment]
PEP 523 is for the C API; none of it is exposed to Python code.
