### ISSUE TITLE
Tagged pointer support

### ISSUE THREAD

**Issue by DinoV** [Microsoft/Pyjion#3]
If we know we have non-escaping integer values we should omit tagged pointer support. That should improve integer arithmetic performance while still supporting overflow to long ints. We should only do it on non-escaping values to avoid repeatedly needing to rebox values.

**Comment by brettcannon** [comment]
Is there more work to do on this or is it finished?

**Comment by DinoV** [comment]
It's done, we need to improve our escape analysis but that's probably orthogonal
