### ISSUE TITLE
2to3 & chameleon_v2 benchmark crashing on POP_JUMP_IF_FALSE

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/Pyjion#75]
https://github.com/Microsoft/Pyjion/blob/master/Pyjion/absint.cpp#L2401 crashes with an out-of-bounds exception on the vector.

**Comment by brettcannon** [comment]
The 2to3 failure is happening in [Lib/os.py:walk()](https://hg.python.org/cpython/file/default/Lib/os.py#l296).

**Comment by DinoV** [comment]
2to3 is passing now, chameleon_v2 is failing for me both w/ jit and w/o
